# permissions for end users to view kafkaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafkacluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: odin
    app.kubernetes.io/part-of: odin
    app.kubernetes.io/managed-by: kustomize
  name: kafkacluster-viewer-role
rules:
- apiGroups:
  - chiu.my.domain
  resources:
  - kafkaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chiu.my.domain
  resources:
  - kafkaclusters/status
  verbs:
  - get
